import streamlit as st
import pickle
import numpy as np
import shap

# Load model and scaler
model = pickle.load(open("breast_cancer_model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

st.title("🏥 AI Breast Cancer Diagnosis System")

# ---------------- Patient Information ----------------

st.subheader("👩 Patient Information")

name = st.text_input("Patient Name")
age = st.number_input("Age", 1, 120)
gender = st.selectbox("Gender", ["Female", "Male"])
patient_id = st.text_input("Patient ID")
doctor = st.text_input("Doctor Name")

# ---------------- Tumor Measurements ----------------

st.subheader("🔬 Tumor Measurements")

radius = st.number_input("Mean Radius")
texture = st.number_input("Mean Texture")
perimeter = st.number_input("Mean Perimeter")
area = st.number_input("Mean Area")
concave_points = st.number_input("Mean Concave Points")

feature_names = [
    "Mean Radius",
    "Mean Texture",
    "Mean Perimeter",
    "Mean Area",
    "Mean Concave Points"
]

if st.button("Analyze Tumor"):

    input_data = np.array([[radius, texture, perimeter, area, concave_points]])
    input_scaled = scaler.transform(input_data)

    prediction = model.predict(input_scaled)
    probability = model.predict_proba(input_scaled)

    st.subheader("📊 Diagnosis Result")

    # ⚠️ IMPORTANT FIX: dataset labels
    # 0 = Malignant
    # 1 = Benign

    if prediction[0] == 0:
        st.error("⚠️ Malignant Tumor Detected")
        result = "Malignant"
    else:
        st.success("✅ Benign (Non‑Cancerous)")
        result = "Benign"

    confidence = np.max(probability) * 100
    st.write(f"Confidence Level: {confidence:.2f}%")

    # ---------------- SHAP Explainability ----------------

    st.subheader("🔍 Main Influencing Feature")

    try:
        explainer = shap.TreeExplainer(model)
        shap_values = explainer.shap_values(input_scaled)

        if isinstance(shap_values, list):
            shap_array = shap_values[0]
        else:
            shap_array = shap_values

        shap_array = np.array(shap_array).flatten()
        shap_array = shap_array[:len(feature_names)]

        importance = np.abs(shap_array)
        top_feature_index = np.argmax(importance)
        top_feature = feature_names[top_feature_index]

        st.info(f"Most Influential Feature: {top_feature}")

    except:
        top_feature = "Unavailable"
        st.info("Feature importance could not be calculated.")

    # ---------------- Counterfactual Suggestion ----------------

    st.subheader("🔄 Counterfactual Suggestion")

    suggestions_found = False

    for i in range(len(feature_names)):

        temp = input_data.copy()
        temp[0][i] = temp[0][i] * 0.8

        temp_scaled = scaler.transform(temp)
        new_pred = model.predict(temp_scaled)

        if new_pred[0] == 1:

            st.write(
                f"If **{feature_names[i]}** decreases slightly, the prediction may change to **Benign**."
            )
            suggestions_found = True

    if not suggestions_found:
        st.info("No small adjustment could change the prediction to benign.")

    # ---------------- Patient Receipt ----------------

    st.subheader("🧾 Patient Diagnosis Receipt")

    receipt = f"""
========================================
        HOSPITAL DIAGNOSTIC REPORT
========================================

Patient Name : {name}
Age          : {age}
Gender       : {gender}
Patient ID   : {patient_id}
Doctor       : {doctor}

----------------------------------------
Tumor Measurements
----------------------------------------
Mean Radius          : {radius}
Mean Texture         : {texture}
Mean Perimeter       : {perimeter}
Mean Area            : {area}
Mean Concave Points  : {concave_points}

----------------------------------------
AI Diagnosis Result
----------------------------------------
Prediction : {result}
Confidence : {confidence:.2f} %

Main Influencing Feature :
{top_feature}

----------------------------------------
Generated by AI Breast Cancer
Diagnostic System
----------------------------------------
"""

    st.download_button(
        label="🧾 Download Diagnosis Receipt",
        data=receipt,
        file_name="patient_diagnosis_receipt.txt",
        mime="text/plain"
    )

    st.success("AI Diagnostic Report Generated Successfully")